repos:
- repo: local
  hooks:
  - id: black
    name: black
    language: system
    entry: black --check
    types: [python]

  - id: bandit
    name: bandit
    language: system
    entry: bandit --recursive --skip B101,B324 src  # B101 is assert statements
    types: [python]
#  - id: isort
#    name: isort
#    language: system
#    entry: isort --check-only
#    types: [python]